### ISSUE TITLE
金标准有问题

### ISSUE THREAD

**Issue by jarork** [wzzzd/pretrain_bert_with_maskLM#2]
datasets里面train.txt和test.txt里面的文本有UNK标识，导致训练的时候金标准和训练样本一致，结果就是最后训练出来的模型我用来预测[MASK]的时候发现，出来的都是[MASK]。。

断点打在train.py第70行位置，watch一下list(zip(batch['input_ids'][0].tolist(), batch['labels'][0].tolist()))，会发现input_ids和labels是一模一样的。

**Comment by jarork** [comment]
经过检查我发现只有wwm模式有这个问题，把wwm改成false是正常的

**Comment by wzzzd** [comment]
> 

经过debug后，发现确实是。
定位到是变量引用的问题。也就是token.data['labels']和token.data['input_ids']刚开始是同一个对象指向。
当初赋值给token.data['labels']的时候只用了浅拷贝，所以后面token.data['input_ids']被修改后，token.data['labels']也跟着变了。

解决方法是，变量赋值改成深拷贝。即将
token.data['labels'] = token.data['input_ids']
改为
import copy
label=copy.deepcopy(token.data['input_ids'])
token.data['labels'] = label

感谢反馈，已更新了代码。^^

**Comment by jarork** [comment]
谢谢
