### ISSUE TITLE
请教个人数据集预训练的问题

### ISSUE THREAD

**Issue by minlik** [wzzzd/pretrain_bert_with_maskLM#6]
请教一下，如果要使用个人搜集的中文数据集进行wwm预训练，

1. 是否要预先进行分词后再进行存储？
2. 如果数据集中某一行的文本过长，需要分成好几行送入模型吗？例如，文本过长的话，是否要根据句子标识符，或者根据max_length分成若干行？

**Comment by wzzzd** [comment]
你好。

1.如果是中文的话，可以预先通过第三方的package，比如jieba、lac等，分词、替换成[MASK]，在存储。在读取的时候，如果是用transformers的bert分词器，那么能识别这个[MASK]的字符。这样会比每次跑程序都分词+mask操作速度要快。

2.建议是截断成若干行，或改成用基于相对位置编码类的模型会比较友好。虽然可以通过max_length来设置长度，不过开源的bert参数基本都是限定为512长度。长度如果再长的话，由于受attention的O(n²)限制，会影响训练效率。

**Comment by minlik** [comment]
感谢回复。

另外对于第二个问题，如果是截断的话，是根据文本中的句子截断（比如：利用句号、问号、感叹号等标点符号把长文本截断为若干个短句子），还是固定长度（比如：把长文本截断为若干个固定长度为512的短文本）？

**Comment by wzzzd** [comment]
建议是按照标点符号切，比如。？！；
如果按照这些符号切分后，也超过512，那么可以考虑针对性的使用逗号切分
